spring.application.name=eventify
spring.datasource.url=jdbc:mysql://mysql-2705271a-povilas-080e.d.aivencloud.com:24367/eventify_db?useSSL=true&requireSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub
#spring.jpa.show-sql=true

#MongoDB shenanigans localhost

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=messagedb

#MongoDB shenanigans ATLAS
#spring.data.mongodb.uri=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@eventify.dhc8is1.mongodb.net/messagedb?retryWrites=true&w=majority&appName=eventify

# Caffeine caching
spring.cache.type=caffeine
spring.cache.cache-names=eventsCache
spring.cache.caffeine.spec=expireAfterWrite=15m,maximumSize=500

r2.accessKeyId=${R2_ACCESS_KEY_ID}
r2.secretAccessKey=${R2_SECRET_ACCESS_KEY}
r2.endpointUrl=${R2_ENDPOINT_URL}
r2.region=${R2_REGION}
r2.bucketName=${R2_BUCKET_NAME}