export const staticEventLoader = () => {
  const start = new Date();
  const end = new Date(start.getTime() + 2 * 60 * 60 * 1000);

  return [
    {
      title: 'Event 1',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 2',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 3',
      experienceLevel: 2,
      isRegistered: 1,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 4',
      experienceLevel: 2,
      isRegistered: 1,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 5',
      experienceLevel: 2,
      isRegistered: 1,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 6',
      experienceLevel: 2,
      isRegistered: 1,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 7',
      experienceLevel: 2,
      isRegistered: 1,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 28',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 29',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 30',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 31',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 32',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 33',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 34',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 35',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 36',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 37',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 38',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 39',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 40',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 41',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 42',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 43',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 43',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 43',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 43',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 43',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 43',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 43',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 43',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
    {
      title: 'Event 43',
      experienceLevel: 2,
      isRegistered: 0,
      currentParticipants: 2,
      maxParticipants: 9,
      startDateTime: start,
      endDateTime: end,
      location: 'Paulino g. 20',
      requiredAge: '+18',
    },
  ];
}